### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by harishsave** [gayanSandamal/php-image-resizer#1]
On line # 11, If I change image quality to 80 or 90 etc. then I get following error:

`Warning: imagejpeg() expects parameter 1 to be resource, boolean given`

I checked putting various values. Values only till 20 works. Anything above that gives the same error.

**Comment by gayanSandamal** [comment]
As the image quality already  addressed  in this line it's not necessary to handle in "imagejpeg" method.
https://github.com/gayanSandamal/easy-php-image-resizer/blob/855adeea8cb95e88adb801873bb3dd89e9bd1cbd/php-image-resizer.php#L51
